version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: band_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/band_booking?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
      SMTP_USER: your-email@example.com
      SMTP_PASS: your-email-password
      PORT: 3000
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  frontend:
    build:
      context: ./frontend
      args:
        # The frontend is served to the host's browser, so it must talk to
        # localhost to reach the backend exposed on port 3000.
        - VITE_API_URL=http://localhost:3000/api
    ports:
      - "5173:80"
    environment:
      # Point the frontend to the backend running on the host
      VITE_API_URL: http://localhost:3000/api
    depends_on:
      - backend

volumes:
  postgres_data: 