version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
      DATABASE_URL: postgresql://user:password@db:5432/booking_system?schema=public
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    command: sh -c "npm install && npx prisma generate && npm start"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGS_PASSWORD: password
      POSTGRES_DB: booking_system
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: